package jet.hipics21.business.rules.jumping;

public enum TABLE {
	
	// Pour définir les barèmes
	A, A1AZ, A2AZ, A2U, A2U1AZ, AMER, AZ, AZ1A, AZ1AMER, AZ1AZ, AZ1C, AZ2A, AZ2AZ, AZ2RU, AZ2RU1AM,
	AZ2RU1AZ, AZ2RUSA, AZ2S1A2C, AZ2U, AZ2U1AZ, AZ2UC, AZAZSA, AZAZSA0, ASAZSC0, AZDAC, AZDAP,
	AZDAZ, AZK1AM, AZK1AZ, AZK1C, BARR, C, C1AZ, DERBY, EQUI, JAGD, KNOCK, KOMB, PROG, PROGJO, PUIS,
	PUNKT, ZEIT, ZWEIPH;

}
