package jet.hipics21.business.official;

public enum JudgeQualification {

	DRESSAGE_PRESIDENT, DRESSAGE_LETTER_C, DRESSAGE_LETTER_H, DRESSAGE_LETTER_E, DRESSAGE_LETTER_B, DRESSAGE_LETTER_M, 
	DRESSAGE_SGP, DRESSAGE_S, DRESSAGE_M, DRESSAGE_L, DRESSAGE_FB, DRESSAGE_ASSISTANT,
	DRESSAGE_TECHN_DELEGUE, DRESSAGE_LICENCE, DRESSAGE_FEI;
}
