package jet.hipics21.business.official;

public enum OfficialFunction {
	ASPIRANT_CONSTRUCT_CC, ASPIRANT_JUGE_CC, ASPIRANT_JUGE_ATTELAGE, ASPIRANT_JUGE_DRESSAGE_L, ASPIRANT_JUGE_NATIONAL_SAUT,
	ASSISTANT_CONSTRUCT_ATTELAGE, ATTELAGE_TD_PRESIDENT_JURY, 
	CANDIDAT_CONSTRUCT_FEI_ATTELAGE, CANDIDAT_JUGE_FEI_SAUT, 
	CONSTRUCTEUR_PARCOURS, CONSTRUCTEUR_PARCOURS_CC,
	TD_CC, TD_DRESSAGE, 
	JUGE_A_BREVET, JUGE_B_BREVET, JUGE_ATTELAGE, JUGE_CC,
	JUGE_DRESSAGE_FB, JUGE_DRESSAGE_L, JUGE_DRESSAGE_M, JUGE_DRESSAGE_S_PETIT, JUGE_DRESSAGE_S_GRAND,
	JUGE_LICENCE, JUGE_STYLE,
	JUGE_INTERNA_FEI_CC, JUGE_INTERNA_FEI_DRESSAGE, JUGE_INTERNA_FEI_SAUT,
	JUGE_NATIONAL_SAUT,
	JUGE_OFFICIEL_FEI_DRESSAGE, JUGE_OFFICIEL_FEI_SAUT,
	PRESIDENT_JURY_CC, PRESIDENT_JURY_SAUT,
	VETERINAIRE, MEDECIN;

}
